
default:
	./jemdoc.py -c site.conf -o ../ index.jemdoc
	./jemdoc.py -c site.conf -o ../ aboutme.jemdoc
	./jemdoc.py -c site.conf -o ../ biography.jemdoc
	./jemdoc.py -c site.conf -o ../ research.jemdoc
	./jemdoc.py -c site.conf -o ../ publications.jemdoc
	./jemdoc.py -c site.conf -o ../ student-opportunities.jemdoc
	./jemdoc.py -c site.conf -o ../ mentees.jemdoc
	./jemdoc.py -c site.conf -o ../ recent.jemdoc
	./jemdoc.py -c site.conf -o ../ teaching-past.jemdoc
	./jemdoc.py -c site.conf -o ../ archive/comparchproject.jemdoc 
	./jemdoc.py -c site.conf -o ../ archive/mtechproject.jemdoc 

